"""Data models for the RAG writing assistant."""

from .common import (
    ConfidenceLevel,
    CoverageDescriptor,
    DocumentCoverage,
    DocumentRegion,
    GeneratedSection,
    IntentClassification,
    QueryIntent,
    RetrievalMetadata,
    RetrievalType,
    SourceReference,
    SummaryScope,
    WarningType,
)
from .document import (
    ChunkingConfig,
    Document,
    DocumentChunk,
    DocumentMetadata,
    DocumentStatus,
    DocumentType,
)
from .generation import (
    CoverageDescriptorResponse,
    DocumentCoverageResponse,
    GeneratedSectionResponse,
    GenerationRequest,
    GenerationResponse,
    GenerationResult,
    IntentClassificationResponse,
    RegenerateSectionRequest,
    RegenerateSectionResponse,
    RegenerationResult,
    RetrievalMetadataResponse,
    SourceReferenceResponse,
    SuggestedQuestionsRequest,
    SuggestedQuestionsResponse,
)

__all__ = [
    # Common
    "ConfidenceLevel",
    "CoverageDescriptor",
    "DocumentCoverage",
    "DocumentRegion",
    "GeneratedSection",
    "IntentClassification",
    "QueryIntent",
    "RetrievalMetadata",
    "RetrievalType",
    "SourceReference",
    "SummaryScope",
    "WarningType",
    # Document
    "ChunkingConfig",
    "Document",
    "DocumentChunk",
    "DocumentMetadata",
    "DocumentStatus",
    "DocumentType",
    # Generation
    "CoverageDescriptorResponse",
    "DocumentCoverageResponse",
    "GeneratedSectionResponse",
    "GenerationRequest",
    "GenerationResponse",
    "GenerationResult",
    "IntentClassificationResponse",
    "RegenerateSectionRequest",
    "RegenerateSectionResponse",
    "RegenerationResult",
    "RetrievalMetadataResponse",
    "SourceReferenceResponse",
    "SuggestedQuestionsRequest",
    "SuggestedQuestionsResponse",
]
